# Generated by Django 5.0.1 on 2024-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0003_estabelecimento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
