# Generated by Django 5.0.1 on 2024-01-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estabelecimentos', '0004_alter_estabelecimento_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
