# Generated by Django 5.0.1 on 2024-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img_video',
            field=models.ImageField(null=True, upload_to='img_about_video'),
        ),
        migrations.AddField(
            model_name='about',
            name='lnk_video',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.ImageField(upload_to='img_about'),
        ),
    ]
