# Generated by Django 5.0.1 on 2024-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
